### ISSUE TITLE
"Susca" and non bidirectional friends

### ISSUE THREAD

**Issue by j3yxz** [AngeloFilaseta/vocabolangelo-rdf#13] opened 2022-08-12 19:08 UTC
We really need to solve this, the easier way to do it may be to define a new relationship, something like "unpaidFriendOf", cause right now Matteo Susca and Nicole Battaglino are friends and we can't make "friendOf" unilateral as we might need a lot of replication in the .ttl file

**Comment by AngeloFilaseta** [comment] 2022-08-12 19:37
We'll talk about this in real life

**Comment by AngeloFilaseta** [comment] 2022-08-16 11:22
I added a new property, `vocang:unpaidFriendOf`, that does exactly what you requested. I also added the tuples on `vocang:suscaMatteo`. This issue cannot be closed yet, as we need a reasoner that works to make the `rel:friendOf` property symmetric for real.

**Comment by j3yxz** [comment] 2022-08-16 11:38
Ok that is nice, i can use that to create oriented friends graph, then when the reasoner will be ready friends will be listed on each Creator's page!

**Comment by AngeloFilaseta** [comment] 2022-08-16 17:17
The reasoner is now working fine. Some automation steps are required now.

You can already use the inferred file, but you need to do as follow (for now):

1. Assuming you are using Arch, requirements are [Pellet](https://aur.archlinux.org/packages/pellet) and [Apache Jena](https://aur.archlinux.org/packages/apache-jena).
2. run `gradle infer` in the repo directory. A new file should pop out in the `_data` folder named `vocabolangelo-merged.ttl`
3. In the `_config.yml` file change the path from `"_data/vocabolangelo.ttl"` to `"_data/vocabolangelo-merged.ttl"`

Done.

**Comment by AngeloFilaseta** [comment] 2022-08-24 09:58
Closing this issue as the problem is solved, I'll create another issue for the reasoner worflow creation

**Closed as completed by AngeloFilaseta** 2022-08-24 09:58 UTC
